DOD code merge to run 21.
pcdshub/mfx pull request #46
Opened 2024-01-31 20:10 UTC by lg345

2024-01-31 20:31 UTC, gadorlhiac requested changes
Looks fine to me - @lg345 can you decide on the naming for the `lxe` object? Otherwise a couple quick changes and it can be merged.

2024-01-31 20:31 UTC, gadorlhiac commented on mfx/beamline.py
> +        lxe_pw = LXE("MFX:LAS:MMN:08", calibration_file=lxe_calib_file, name="lxe_pw")
Are people happy with this nomenclature? When I added it in I didn't want to conflict with any objects others may have been trying to create at the time. If you'd prefer `lxe` to `lxe_pw` we should probably make that change before merging. It's probably useful to keep things consistent with muscle memory people have from moving between hutches?

2024-01-31 20:31 UTC, gadorlhiac commented on mfx/beamline.py~
This file should be untracked and removed. It's a backup emacs file which is not needed in the repo.

2024-01-31 20:31 UTC, gadorlhiac commented on mfx/focus_scan.py
Looks fine to me. This was tested and found to still work during `mfxx1006522` right?

2024-02-01 19:57 UTC, lg345 commented on mfx/beamline.py
> +        lxe_pw = LXE("MFX:LAS:MMN:08", calibration_file=lxe_calib_file, name="lxe_pw")
lxe will be the final name for the object.

2024-02-05 17:26 UTC, merged